spring:
  profiles: default
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
server:
  port: 8014
words: reasonable,leaky,suspicious,ordinary,unlikely